apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mncad3vm9-go
  janus-idp.io/tekton: mncad3vm9-go
  backstage.io/kubernetes-id: mncad3vm9-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mncad3vm9-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
